all:
  hosts:
    web1:
    #esto tomara el valor de la secret
      ansible_host: "{{ lookup('env','REMOTE_HOST') }}"
      ansible_port: 22
      ansible_user: deploy
      ansible_python_interpreter: /usr/bin/python3